CREATE DATABASE IF NOT EXISTS exercicio_CRUD_jdbc;

USE exercicio_CRUD_jdbc;

CREATE TABLE IF NOT EXISTS clientes(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    idade INT UNSIGNED NOT NULL,
    cpf VARCHAR(15) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    PRIMARY KEY (id)
);
